name: 'size'
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  react-size:
    runs-on: namespace-profile-2vcpu-cache
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - uses: andresz1/size-limit-action@f338c35e16e2643dcc41a8ba32fbaf0ec9016728 # with pnpm support
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          script: pnpm --filter @livekit/components-react exec size-limit --json
          package_manager: pnpm
          build_script: build:react
